---
driver:
   name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.0.3
  data_path: test/fixtures

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  attributes:
    machine_fqdn: dataops.flugel.it
    machine_fqdn_as_hostname: true
  run_list:
  - recipe[fqdn]
  - recipe[apache2_test::setup]
  - recipe[apache2_test::default]
  - recipe[apache2_test::basic_web_app]

